apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  selector:
    matchLabels: # posts-depl va a tomar como suyos todos los pods que tengan una etiqueta app: post
      app: posts
  template: # me ayuda a definir metadata a los objetos del deployment
    metadata:
      labels: #agrego una etiqueta a los recursos que estan en deployment
        app: posts
    spec:
      containers:
        - name: posts
          image: bantrab/ms-posts:0.0.1
          imagePullPolicy: Never
